name: dzechtv

on:
  schedule:
    - cron: '10-59/50 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "dzechtv bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests

      - name: fetch content dzechtv
        run: |
          final_url=$(python3 ressources/kuw/dzechtv.py)
          echo "echstrm=${final_url}" >> $GITHUB_ENV

      - name: Replace Text
        run: |
          echo "echstrm=${echstrm}"
          sed -i "s|live/EchoroukTV.*|${echstrm}|" all.m3u
          sed -i "s|live/EchoroukTV.*|${echstrm}|" ressources/allgr.m3u

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git add all.m3u ressources/allgr.m3u
          git commit -m "dzechorouk updated"
          git push
