name: dzhayat action

on:
  schedule:
    - cron: '*/50 * * * *'
  
  workflow_dispatch:

jobs:
  download_video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3



      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  

      - name: Install yt-dlp Python package
        run: pip install yt-dlp

      - name: fetch content dzhayat
        run: python3 ressources/kuw/dzhayat.py > ressources/kuw/dzhayat.m3u8

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "dzhayat bot"
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull origin master
          git commit -m "dzhayat updated"
          git push origin master
